spring.datasource.url=jdbc:h2:file:./db_cgb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sio
spring.datasource.password=slam
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Activer la console H2 pour le débogage
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuration pour l'initialisation de la base de données
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Afficher les requêtes SQL pour le débogage
spring.jpa.show-sql=true

# Configuration du port du serveur
server.port=8080

# Configuration validation IBAN
cgb.iban.strict-validation=false

# Configuration email
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=""
spring.mail.password=""
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.fallback=false

# Configuration des timeouts SMTP
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Adresse email de destination pour les notifications
notification.email=""