# Configuration de la base de données pour les tests
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Désactiver l'initialisation SQL
spring.sql.init.mode=never

# Afficher les requêtes SQL pour le débogage
spring.jpa.show-sql=true

# Désactiver la sécurité pour les tests
spring.security.user.name=user
spring.security.user.password=password 